batch_size: 256
cv_folds: 5
drop_rate: 0.4
graph: snp_interaction
heads: 6
hidden_dim: 128
out_dim: 2
lr: 0.001
log_dir: log
model: MOGT
neighbors: [-1, -1]
num_epochs: 500
disease : SCZ
project: MOGT
random_seed: 42
stable : True
out_dir: outs
wandb: False
weight_decay: 0.05
edge_threshhold : 1
random : False
best : True
num_prototypes_per_class : 7